trigger:
- develop

pr: none

pool:
  vmImage: 'sanju'

stages:
- stage: DeployToAKS
  jobs:
  - job: DeployJob
    steps:
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
